In [1]:
import frame_for_notebooks as frame
import pandas as pd

In [2]:
match_info = frame.build_match_info()
match_info

,match_id,league,season,home_team,away_team,date,time,day_of_week,home_is_promoted,away_is_promoted,...,avg_draw_odds,avg_away_odds,b365_home_impl,b365_draw_impl,b365_away_impl,avg_home_impl,avg_draw_impl,avg_away_impl,b365_margin,avg_margin
0,86a52607af3b0c53992a8a9fddef1d48,england,2223,Crystal Palace,Arsenal,2022-08-05,20:00,Friday,False,False,...,3.59,1.88,0.238095,0.277778,0.540541,0.227790,0.278552,0.531915,0.056414,0.038257
1,e1b72fd88ebbf538d5cafc97b8fe5d2d,england,2223,Fulham,Liverpool,2022-08-06,12:30,Saturday,True,False,...,6.05,1.28,0.090909,0.166667,0.800000,0.090992,0.165289,0.781250,0.057576,0.037531
2,cebc2fc76e319a58f9bb0254542fe0c2,england,2223,Bournemouth,Aston Villa,2022-08-06,15:00,Saturday,True,False,...,3.50,2.04,0.266667,0.285714,0.500000,0.263158,0.285714,0.490196,0.052381,0.039068
3,30d4047674940a6d8886fbda2c5e3544,england,2223,Leeds,Wolves,2022-08-06,15:00,Saturday,False,False,...,3.34,3.18,0.444444,0.294118,0.312500,0.427350,0.299401,0.314465,0.051062,0.041217
4,dd93e9122a0b4f34cf28a20e3ccd2b5b,england,2223,Newcastle,Nott'm Forest,2022-08-06,15:00,Saturday,False,True,...,3.80,5.57,0.602410,0.263158,0.190476,0.598802,0.263158,0.179533,0.056044,0.041494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7076,73d06d765606e35eec658d6407e098dd,france,2526,Lyon,Lens,2026-05-17,20:00,Sunday,False,False,...,4.03,4.04,0.578035,0.250000,0.243902,0.578035,0.248139,0.247525,0.071937,0.073698
7077,81f36d0977e7c5eee2e843053422cabb,france,2526,Marseille,Rennes,2026-05-17,20:00,Sunday,False,False,...,3.69,3.33,0.512821,0.270270,0.307692,0.502513,0.271003,0.300300,0.090783,0.073816
7078,fca5c2f96776f2be1f78aa7f707e8e75,france,2526,Nice,Metz,2026-05-17,20:00,Sunday,False,True,...,5.09,7.75,0.735294,0.200000,0.142857,0.746269,0.196464,0.129032,0.078151,0.071765
7079,6576c1b28cd84f0884785ec63746c222,france,2526,Paris FC,Paris SG,2026-05-17,20:00,Sunday,True,False,...,4.54,1.52,0.181818,0.243902,0.653595,0.194175,0.220264,0.657895,0.079315,0.072334
7080,08ed55cde337ac81fe59678770033bc8,france,2526,Strasbourg,Monaco,2026-05-17,20:00,Sunday,False,False,...,3.83,2.15,0.347222,0.263158,0.476190,0.349650,0.261097,0.465116,0.086571,0.075863

In [3]:
match_info.columns

Index(['match_id', 'league', 'season', 'home_team', 'away_team', 'date',
       'time', 'day_of_week', 'home_is_promoted', 'away_is_promoted',
       'travel_distance_km', 'b365_home_odds', 'b365_draw_odds',
       'b365_away_odds', 'avg_home_odds', 'avg_draw_odds', 'avg_away_odds',
       'b365_home_impl', 'b365_draw_impl', 'b365_away_impl', 'avg_home_impl',
       'avg_draw_impl', 'avg_away_impl', 'b365_margin', 'avg_margin'],
      dtype='str')

In [4]:
match_target = frame.build_match_target()
match_target

,match_id,home_goals,away_goals,result,is_home_win,is_draw,is_away_win,home_goals_diff,goals_total
0,86a52607af3b0c53992a8a9fddef1d48,0,2,A,False,False,True,-2,2
1,e1b72fd88ebbf538d5cafc97b8fe5d2d,2,2,D,False,True,False,0,4
2,cebc2fc76e319a58f9bb0254542fe0c2,2,0,H,True,False,False,2,2
3,30d4047674940a6d8886fbda2c5e3544,2,1,H,True,False,False,1,3
4,dd93e9122a0b4f34cf28a20e3ccd2b5b,2,0,H,True,False,False,2,2
...,...,...,...,...,...,...,...,...,...
7076,73d06d765606e35eec658d6407e098dd,0,4,A,False,False,True,-4,4
7077,81f36d0977e7c5eee2e843053422cabb,3,1,H,True,False,False,2,4
7078,fca5c2f96776f2be1f78aa7f707e8e75,0,0,D,False,True,False,0,0
7079,6576c1b28cd84f0884785ec63746c222,2,1,H,True,False,False,1,3
7080,08ed55cde337ac81fe59678770033bc8,5,4,H,True,False,False,1,9

In [5]:
match_team_stats = frame.build_match_team_stats()
match_team_stats

,match_id,league,season,date,home_team,away_team,home_game_number,away_game_number,home_season_goals_for_avg,home_season_goals_against_avg,...,away_season_goals_against_ge2_ratio,away_season_goals_against_ge3_ratio,home_season_shots_on_target_for_ratio,home_season_shots_on_target_against_ratio,away_season_shots_on_target_for_ratio,away_season_shots_on_target_against_ratio,home_season_red_for_avg,away_season_red_for_avg,home_red_last_match,away_red_last_match
0,a769f5d344aaca5dba9f23b7443ebe4d,england,2223,2022-08-13,Arsenal,Leicester,2,2,2.000000,0.000000,...,1.000000,0.000000,0.200000,0.200000,0.357143,0.375000,0.000000,0.000000,False,False
1,fc1532be1649525e0257243e7660f46b,england,2223,2022-08-27,Arsenal,Fulham,4,4,3.000000,0.666667,...,0.666667,0.000000,0.348837,0.227273,0.416667,0.322581,0.000000,0.000000,False,False
2,dc70b5d371e9877d8ad5d743741615b9,england,2223,2022-08-31,Arsenal,Aston Villa,5,5,2.750000,0.750000,...,0.500000,0.250000,0.353846,0.242424,0.285714,0.391304,0.000000,0.000000,False,False
3,21787c76040fd372dee5d6b762a35871,england,2223,2022-10-01,Arsenal,Tottenham,8,8,2.428571,1.000000,...,0.285714,0.000000,0.362069,0.365385,0.449541,0.219048,0.000000,0.000000,False,False
4,70e3f92c52fc55f7da56c903d3459902,england,2223,2022-10-09,Arsenal,Liverpool,9,8,2.500000,1.000000,...,0.428571,0.142857,0.369565,0.372881,0.348485,0.396552,0.000000,0.142857,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7076,a0015e7a17aa76a6c7eaf19d662fd51d,spain,2526,2026-03-20,Villarreal,Sociedad,29,29,1.821429,1.178571,...,0.357143,0.178571,0.373134,0.284507,0.373961,0.313351,0.107143,0.107143,False,False
7077,88c459fd2e81cba9293c7531ba889195,spain,2526,2026-04-26,Villarreal,Celta,33,33,1.781250,1.156250,...,0.343750,0.125000,0.375000,0.285366,0.395280,0.344737,0.093750,0.031250,False,False
7078,621ad634cf374d85e66fa73d4240e2fc,spain,2526,2026-05-02,Villarreal,Levante,34,34,1.787879,1.151515,...,0.515152,0.181818,0.372796,0.286396,0.303109,0.322457,0.090909,0.121212,False,False
7079,9eadc9b650cfd77c08e2df4b03c6651c,spain,2526,2026-05-13,Villarreal,Sevilla,36,36,1.857143,1.142857,...,0.514286,0.171429,0.372642,0.291759,0.309227,0.407507,0.085714,0.142857,False,False
7080,12b970140bee3592cb506c73ebc2d025,spain,2526,2026-05-24,Villarreal,Ath Madrid,38,38,1.810811,1.216216,...,0.324324,0.108108,0.371882,0.299790,0.386503,0.313084,0.081081,0.135135,False,False

In [6]:
team_season = pd.read_parquet(r'c:\Users\twluc\frame\01_data\02_features\team_season.parquet')
team_season.query("team == 'Arsenal' and season == '2526'")

,match_id,league,season,date,team,opponent,is_home,goals_for,goals_against,points,...,season_goals_against_le0_ratio,season_goals_against_le1_ratio,season_goals_for_ge2_ratio,season_goals_for_ge3_ratio,season_goals_against_ge2_ratio,season_goals_against_ge3_ratio,season_shots_on_target_for_ratio,season_shots_on_target_against_ratio,season_red_for_avg,red_last_match
2280,be601d66d1b858ab42bda85b7ace6c0b,england,2526,2025-08-17,Arsenal,Man United,False,1,0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
2281,e2998bcd21fc0797a644b97ce0ebb44e,england,2526,2025-08-23,Arsenal,Leeds,True,5,0,3,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.318182,0.0,False
2282,c5b11217e27bebe9694cf0d44bb0a2c2,england,2526,2025-08-31,Arsenal,Liverpool,False,0,1,0,...,1.000000,1.000000,0.500000,0.500000,0.000000,0.000000,0.296296,0.320000,0.0,False
2283,efbc801972f317200aad9da0e5ae0423,england,2526,2025-09-13,Arsenal,Nott'm Forest,True,3,0,3,...,0.666667,1.000000,0.333333,0.333333,0.000000,0.000000,0.236842,0.323529,0.0,False
2284,7a2985eb1db0fb662b68c08ec48abe0a,england,2526,2025-09-21,Arsenal,Man City,True,1,1,1,...,0.750000,1.000000,0.500000,0.500000,0.000000,0.000000,0.259259,0.307692,0.0,False
2285,30e286857f28929c2d8678a1bf3fb711,england,2526,2025-09-28,Arsenal,Newcastle,False,2,1,3,...,0.600000,1.000000,0.400000,0.400000,0.000000,0.000000,0.257576,0.340909,0.0,False
2286,5ac64081325e7967e38af9e2ce439b81,england,2526,2025-10-04,Arsenal,West Ham,True,2,0,3,...,0.500000,1.000000,0.500000,0.333333,0.000000,0.000000,0.279070,0.346154,0.0,False
2287,2f0c3b46837f0fcf0bd5f7f5d19f7811,england,2526,2025-10-18,Arsenal,Fulham,False,1,0,3,...,0.571429,1.000000,0.571429,0.285714,0.000000,0.000000,0.271028,0.321429,0.0,False
2288,4c87a18d4970e77cd29c893f812e9dd6,england,2526,2025-10-26,Arsenal,Crystal Palace,True,1,0,3,...,0.625000,1.000000,0.500000,0.250000,0.000000,0.000000,0.276423,0.276923,0.0,False
2289,f8d0bd43a5c40ce0077504abf0b99b45,england,2526,2025-11-01,Arsenal,Burnley,False,2,0,3,...,0.666667,1.000000,0.444444,0.222222,0.000000,0.000000,0.278195,0.263889,0.0,False
2290,5edb67d5d08b59545362fc9b7e82bf5f,england,2526,2025-11-08,Arsenal,Sunderland,False,2,2,1,...,0.700000,1.000000,0.500000,0.200000,0.000000,0.000000,0.310345,0.253333,0.0,False
2291,cc683ae9fe866966f4fda370f85cbc2f,england,2526,2025-11-23,Arsenal,Tottenham,True,4,1,3,...,0.636364,0.909091,0.545455,0.181818,0.090909,0.000000,0.320988,0.259259,0.0,False
2292,3fb161e95e22f76ca990ca2057f731c4,england,2526,2025-11-30,Arsenal,Chelsea,False,1,1,1,...,0.583333,0.916667,0.583333,0.250000,0.083333,0.000000,0.335196,0.273810,0.0,False
2293,09c0877fb3152f1f714c1bfce80f0b82,england,2526,2025-12-03,Arsenal,Brentford,True,2,0,3,...,0.538462,0.923077,0.538462,0.230769,0.076923,0.000000,0.342246,0.284211,0.0,False
2294,91a0abcbf8ab5298dde8fd23dcbafa04,england,2526,2025-12-06,Arsenal,Aston Villa,False,1,2,0,...,0.571429,0.928571,0.571429,0.214286,0.071429,0.000000,0.351485,0.277228,0.0,False
2295,34b5ea10a81edad35cc4f771a7209349,england,2526,2025-12-13,Arsenal,Wolves,True,2,1,3,...,0.533333,0.866667,0.533333,0.200000,0.133333,0.000000,0.368664,0.293103,0.0,False
2296,6abc2a304f194e1ab3aa6b278e1a96e0,england,2526,2025-12-20,Arsenal,Everton,False,1,0,3,...,0.500000,0.875000,0.562500,0.187500,0.125000,0.000000,0.351931,0.302521,0.0,False
2297,ca2ad84537c4e0032b0ca39da6792ec8,england,2526,2025-12-27,Arsenal,Brighton,True,2,1,3,...,0.529412,0.882353,0.529412,0.176471,0.117647,0.000000,0.341463,0.298387,0.0,False
2298,23ebb92b63c88bbabc2995a370a44ba2,england,2526,2025-12-30,Arsenal,Aston Villa,True,4,1,3,...,0.500000,0.888889,0.555556,0.166667,0.111111,0.000000,0.333333,0.303030,0.0,False
2299,2249023dbf0c254cc377d5b04bb42bf7,england,2526,2026-01-03,Arsenal,Bournemouth,False,3,2,3,...,0.473684,0.894737,0.578947,0.210526,0.105263,0.000000,0.332192,0.300699,0.0,False
2300,b8988bc6f1d356ab60ae39a80262f595,england,2526,2026-01-08,Arsenal,Liverpool,True,0,0,1,...,0.450000,0.850000,0.600000,0.250000,0.150000,0.000000,0.335526,0.291139,0.0,False
2301,be96462e622def5eea79e8fc65523e2c,england,2526,2026-01-17,Arsenal,Nott'm Forest,False,0,0,1,...,0.476190,0.857143,0.571429,0.238095,0.142857,0.000000,0.338658,0.277108,0.0,False
2302,82420aa306777e1393a2086e77538413,england,2526,2026-01-25,Arsenal,Man United,True,2,3,0,...,0.500000,0.863636,0.545455,0.227273,0.136364,0.000000,0.332317,0.267442,0.0,False
2303,8ba593d6ab9b538841decfb4ee462ef4,england,2526,2026-01-31,Arsenal,Leeds,False,4,0,3,...,0.478261,0.826087,0.565217,0.217391,0.173913,0.043478,0.329446,0.269231,0.0,False
2304,7514bf7c511f3e0cd4b4e2d86c0a4dcb,england,2526,2026-02-07,Arsenal,Sunderland,True,3,0,3,...,0.500000,0.833333,0.583333,0.250000,0.166667,0.041667,0.338936,0.270270,0.0,False
2305,eb4e3c99993f8e7ae372f82f27e69d83,england,2526,2026-02-12,Arsenal,Brentford,False,1,1,1,...,0.520000,0.840000,0.600000,0.280000,0.160000,0.040000,0.337802,0.278947,0.0,False
2306,35c22e60dd613c320264aa837b8065c0,england,2526,2026-02-18,Arsenal,Wolves,False,2,2,1,...,0.500000,0.846154,0.576923,0.269231,0.153846,0.038462,0.336842,0.277228,0.0,False
2307,b4e5e30fd86353d734e002260a78d345,england,2526,2026-02-22,Arsenal,Tottenham,False,4,1,3,...,0.481481,0.814815,0.592593,0.259259,0.185185,0.037037,0.338462,0.280193,0.0,False
2308,86e80e65528df3d19f17fd812b838887,england,2526,2026-03-01,Arsenal,Chelsea,True,2,1,3,...,0.464286,0.821429,0.607143,0.285714,0.178571,0.035714,0.339024,0.295775,0.0,False
2309,6b90ee3ae793838451c6fff7d7d39959,england,2526,2026-03-04,Arsenal,Brighton,False,1,0,3,...,0.448276,0.827586,0.620690,0.275862,0.172414,0.034483,0.341232,0.297297,0.0,False
2310,1eaa34bad5aac3c6fc2ec7f76112aafe,england,2526,2026-03-14,Arsenal,Everton,True,2,0,3,...,0.466667,0.833333,0.600000,0.266667,0.166667,0.033333,0.340326,0.296137,0.0,False
2311,6a26e467e268a98c2bb85abb716efb20,england,2526,2026-04-11,Arsenal,Bournemouth,True,1,2,0,...,0.483871,0.838710,0.612903,0.258065,0.161290,0.032258,0.337004,0.297521,0.0,False
2312,5149ca9df9cef4fcb863fa962a788f04,england,2526,2026-04-19,Arsenal,Man City,False,1,2,0,...,0.468750,0.812500,0.593750,0.250000,0.187500,0.031250,0.332623,0.300000,0.0,False
2313,3776e29789573101ad8a56d2af1d565d,england,2526,2026-04-25,Arsenal,Newcastle,True,1,0,3,...,0.454545,0.787879,0.575758,0.242424,0.212121,0.030303,0.332636,0.301887,0.0,False
2314,223e8575738fb6a7c05628f7912b22c8,england,2526,2026-05-02,Arsenal,Fulham,True,3,0,3,...,0.470588,0.794118,0.558824,0.235294,0.205882,0.029412,0.333333,0.298561,0.0,False
2315,bc1c8881f1a4c37333cc41a8715663e5,england,2526,2026-05-10,Arsenal,West Ham,False,1,0,3,...,0.485714,0.800000,0.571429,0.257143,0.200000,0.028571,0.339250,0.291667,0.0,False
2316,771df3936778d276c9ac6bc8936718ef,england,2526,2026-05-18,Arsenal,Burnley,True,1,0,3,...,0.500000,0.805556,0.555556,0.250000,0.194444,0.027778,0.337165,0.292929,0.0,False
2317,cb8a6f0c7a8c1b98e933751e8d937db6,england,2526,2026-05-24,Arsenal,Crystal Palace,False,2,1,3,...,0.513514,0.810811,0.540541,0.243243,0.189189,0.027027,0.334579,0.288079,0.0,False